#!/usr/bin/perl -w

#v2 - added check for failed backup, returns CRITICAL then! --fu

use Getopt::Std;
getopts('c:h');
use vars qw($opt_c $opt_h);
use Time::Local;

$default_tivoli_check_command = "LANG=C /opt/tivoli/tsm/client/ba/bin/dsmc q files";
$default_backup_partition = "/";
$default_warning_threshold_seconds = 3600 * 36;
$default_critical_threshold_seconds = 3600 * 24 * 30;

if (defined $opt_h) {
    print "$0\n";
    print "\tanalyze tivoli output\n";
    print "\tchecks if last backup is older than some default threshold\n";
    print "\tNagios mode: returns proper exit code and status text\n";
    print "\tOptions:\n";
    print "\t-h this help\n";
    print "\t-c the partition to check, default: '$default_backup_partition' \n";
    print "\t\n";
    exit 0;
}

if (defined $opt_c ) {  
    $default_backup_partition = $opt_c;
}

open IN, "$default_tivoli_check_command|";

$interestingpart = 0;
while (<IN>) {
    if ($interestingpart) {
	#   2   12/08/2011 15:30:50   EXT3    /data       
	/^\s*(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)/;
	$date = $2;
	$time = $3;
	$partition = $5;
	next unless $partition eq $default_backup_partition;
	@d = split "/", $date;
	@t = split ":", $time;

        my $now = time;
        my $thatstart = timelocal ($t[2],$t[1],$t[0],$d[1],$d[0]-1,$d[2]);
        my $difference = $now - $thatstart;

	if ($difference > $default_critical_threshold_seconds) {
	    print "Tivoli Backup for ${default_backup_partition}: CRITICAL, hasn't been run for more than " . int($difference / 3600) . " hours.";
	    exit 2;
	} elsif ($difference > $default_warning_threshold_seconds) {
	    print "Tivoli Backup for ${default_backup_partition}: WARN, hasn't been run for more than " . int($difference / 3600) . " hours.";
	    exit 1;
	} else {
	    print "Tivoli Backup for ${default_backup_partition}: OK, last backup before " . int($difference / 3600) . " hours.";
	    exit 0;
	}
    }
    if (/----------/) {
	$interestingpart = 1;
    }
}

if ($interestingpart==0) {
     print "Tivoli Backup for ${default_backup_partition}: CRITICAL, Tivoli access failure!";
     exit 2;
}
